#!/bin/bash

ME=`whoami`

CDPC_DIR=/usr/local/cdpc
CDPC_WATCH=/tmp/cdpc_watch
CDPC_LOADINFO=/tmp/cdpcd-load.log
CDPC_LOGDIR="$CDPC_DIR/logs"

if [ "$UID" -gt 0 ] ; then
    CDPC_DIR="$HOME/.local/cdpc"
    CDPC_WATCH="$CDPC_DIR/watch"
    CDPC_LOADINFO="$CDPC_DIR/cdpcd-load.log"
    CDPC_LOGDIR="$CDPC_DIR/logs"
fi

if [ ! -d "$CDPC_DIR" ] ; then
    mkdir -p "$CDPC_DIR"
fi

CDPC_CONFIG="$CDPC_DIR/config"

if [ ! -d "$CDPC_CONFIG" ] ; then
    mkdir -p $CDPC_CONFIG
fi

if [ ! -d "$CDPC_LOGDIR" ] ; then
    mkdir -p "$CDPC_LOGDIR"
fi

if [ ! -d "$CDPC_WATCH" ] ; then
    mkdir -p $CDPC_WATCH
fi

CDPC_SERVER="$CDPC_DIR/webserver"

CDPC_SERVER_APP="$CDPC_SERVER/app.js"

ARGS=''

help () {
    if [ -f "/usr/local/cdpc/helpdoc" ] ; then
        man "/usr/local/cdpc/helpdoc"
    fi
}

parse_args () {
    if [ "$#" -gt 0 ] ; then
        
        COUNT=0

        for a in $@ ; do
            let COUNT+=1
            if [ $COUNT -gt 1 ] ; then
                ARGS="$ARGS $a"
            fi
        done

    fi
}

check_args2_exit () {
    if [ "$1" -lt $2 ] ; then
        echo "less arguments."
        exit 1
    fi
}

handle_config () {
    case $1 in
        add)
            if [ ! -f "$2" ] ; then
                echo "$2 : file not exists"
                exit 1
            fi

            cp "$2" "$CDPC_CONFIG/"
            echo "$CDPC_CONFIG/$2" > "$CDPC_WATCH/load"
            ;;

        remove)
            if [ ! -f "$CDPC_CONFIG/$2" ] ; then
                echo "file not exists"
                exit 1
            fi
            rm "$CDPC_CONFIG/$2"
            ;;

        show)
            CFGLIST=`ls $CDPC_CONFIG`
            for c in $CFGLIST ; do
                echo "$CDPC_CONFIG/$c:"
                cat -n "$CDPC_CONFIG/$c"
                echo "    "
            done
            ;;
    esac
}

handle_app () {
    case $1 in
        start)
            ;;

        stop)
            ;;

        restart)
            ;;

        pause)
            ;;
        
        resume)
            ;;

        remove)
            ;;
        *)
            echo "$1 : unknow command"
            return 1
            ;;
    esac

    echo "$ARGS" > $CDPC_WATCH/$1
}

handle_webserver () {
    case $1 in
        start)
            ;;

        stop)
            ;;

        restart)
            ;;

        pause)
            ;;
        
        resume)
            ;;
        *)
            echo "$1 : unknow command"
            return 1
            ;;
    esac

    echo cdpc-web-server > $CDPC_WATCH/$1
}

handle_auth () {
    case $1 in
        add)
            ;;

        remove)
            ;;
        *)
            echo "unknow command"
            exit 1
            ;;
    esac

    node /usr/local/cdpc/auth.js $1 $2
}

parse_args $@

case $1 in
    start)
        check_args2_exit $# 2
        handle_app start $ARGS
        ;;

    stop)
        check_args2_exit $# 2
        handle_app stop $ARGS
        ;;

    restart)
        check_args2_exit $# 2
        handle_app restart $ARGS
        ;;

    pause)
        check_args2_exit $# 2
        handle_app pause $ARGS
        ;;

    resume)
        check_args2_exit $# 2
        handle_app resume $ARGS
        ;;

    reload)
        date > $CDPC_WATCH/reload
        ;;

    log)
        ;;

    status)
        node /usr/local/cdpc/outstatus.js $CDPC_LOADINFO
        ;;
    
    #start stop restart
    webserver)
        check_args2_exit $# 2
        if [ "$UID" -gt 0 ] ; then
            echo "deny!!"
            exit 1
        fi

        handle_webserver $2
        ;;

    config)
        if [[ $# -gt 1 ]] && [[ "$2" = "show" ]] ; then
            handle_config show
            exit 0
        fi

        check_args2_exit $# 3
        handle_config $2 $3
        ;;

    #用户授权
    auth)
        if [[ $# -lt 2 ]] && [[ "$UID" -gt 0 ]] ; then
            if [ ! -f "/usr/local/cdpc/uauth/$ME" ] ; then
                echo "!!还没有被授权(You are not authorized.)"
            else
                echo "已被授权(You have be authorized.)"
            fi

            exit 0
        fi

        if [ "$UID" -gt 0 ] ; then
            echo "deny!!"
            exit 1
        fi

        if [ $# -lt 2 ] ; then
            UAUTH_PATH="/usr/local/cdpc/uauth"

            if [ ! -d "$UAUTH_PATH" ] ; then
                echo 'There is no user auth.'
            else
                ls $UAUTH_PATH
            fi

            exit 0
        fi

        check_args2_exit $# 3

        #[add|remove] [USER]
        handle_auth $2 $3
        ;;

    help)
        help
        ;;
    
    *)
        echo "未知操作命令，可使用cdpc help查看帮助文档"
        exit 0
        ;;
esac
